version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9110:9110"
    env_file:
      - .env
    networks:
      - brewery
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "start"]

  public_frontend:
    build: ./public_frontend
    ports:
      - "9010:9010"
    env_file:
      - .env
    networks:
      - brewery
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]


  protected_frontend:
    build: ./protected_frontend
    ports:
      - "9011:9011"
    env_file:
      - .env
    networks:
      - brewery
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]


  mqtt:
    build: ./mqtt_host
    restart: always
    ports:
      - "1883:1883"
    networks:
      - brewery
    volumes:
      - ./mqtt_host/mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  brewery:
    driver: bridge