# docker-compose.yml
version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "7501:5000"  # Maps container's port 5000 to host's port 7501

  frontend:
    build: ./frontend
    ports:
      - "7500:5000"  # Maps container's port 5000 to host's port 7500
