version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9110:9110"
    env_file:
      - .env
    networks:
      - brewery

  public_frontend:
    build: ./public_frontend
    ports:
      - "9010:9010"
    env_file:
      - .env
    networks:
      - brewery
    depends_on:
      - backend

  protected_frontend:
    build: ./protected_frontend
    ports:
      - "9011:9011"
    env_file:
      - .env
    networks:
      - brewery
    depends_on:
      - backend

  mqtt:
    build: ./mqtt_host
    restart: always
    ports:
      - "1883:1883"
    networks:
      - brewery
    volumes:
      - ./mqtt_host/mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  brewery:
    driver: bridge