FROM python:3.9

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install ping and telnet utilities
RUN apt-get update && apt-get install -y iputils-ping telnet

COPY . .
CMD ["python", "app.py"]
