# Use Node.js as the base image
FROM node:16

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the React app
RUN npm run build

# Expose port 3000 for the frontend app
EXPOSE 4567

# Start the React app
CMD ["npm", "start"]
